[package]
name = "docker-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
inotify = "0.10.2"
ratatui = { version = "0.26.3", features = ["serde"] }
regex = "1.10.5"
walkdir = "2.5.0"
